; Zusammensetzen der Einzeldateien zu CAOS 3.4
; (C) Mario Leubner, 31.05.2021-04.06.2021
;-------------------------------------------------
; CAOS-Vorblock:
	ORG	0E000H-128
	DB	'CAOS34  KCC'
	DS	5,0
	DB	2		; 2 Adressen
	DW	4000H		; AADR
	DW	8000H		; EADR+1
	DS	107,0
;-------------------------------------------------
include	caose.asm		; ROM-E
include zsgross.inc
include	caosfv.asm		; ROM-F
include zsklein.inc
